In [102]:
import pandas as pd

##Import trainsets

In [103]:
train_hsurvey_features = pd.read_csv("train_hh_features.csv")

print("Survey features",'\n',train_hsurvey_features)

train_hconsumption_labels = pd.read_csv("train_hh_gt.csv")

print("Consumption Labels",'\n',train_hconsumption_labels)

train_povrate_labels = pd.read_csv("train_rates_gt.csv")

print("Poverty rate",'\n',train_povrate_labels)

Survey features
           hhid  com  weight  strata  utl_exp_ppp17    male  hsize  \
0       100001    1      75       4      594.80627  Female      1
1       100002    1     150       4     1676.27230  Female      2
2       100003    1     375       4      506.93719    Male      5
3       100004    1     375       4      824.61786    Male      5
4       100005    1     525       4      351.47644    Male      7
...        ...  ...     ...     ...            ...     ...    ...
104229  337458    1     616       7      143.58849  Female      4
104230  337459    1     616       7      268.44803  Female      4
104231  337460    1    1540       7      243.47612    Male     10
104232  337461    1    1232       7      337.12079    Male      8
104233  337462    1     154       7      243.47612  Female      1

        num_children5  num_children10  num_children18  ...  consumed4200  \
0                   0               0               0  ...           Yes
1                   0               0               0  ...           Yes
2                   0               0               2  ...           Yes
3                   0               0               1  ...            No
4                   1               0               0  ...           Yes
...               ...             ...             ...  ...           ...
104229              2               1               0  ...           Yes
104230              0               0               1  ...           Yes
104231              2               3               2  ...           Yes
104232              0               0               3  ...           Yes
104233              0               0               0  ...           Yes

       consumed4300 consumed4400 consumed4500 consumed4600 consumed4700  \
0                No           No           No          Yes          Yes
1                No           No           No           No          Yes
2               Yes           No          Yes          Yes          Yes
3               Yes           No           No           No          Yes
4                No           No          Yes           No          Yes
...             ...          ...          ...          ...          ...
104229           No           No           No           No          Yes
104230           No           No           No           No          Yes
104231           No           No          Yes           No          Yes
104232          Yes           No          Yes           No           No
104233           No           No          Yes           No          Yes

       consumed4800 consumed4900 consumed5000  survey_id
0               Yes          Yes           No     100000
1               Yes           No           No     100000
2               Yes           No          Yes     100000
3               Yes           No           No     100000
4               Yes          Yes           No     100000
...             ...          ...          ...        ...
104229          Yes           No          Yes     300000
104230           No           No           No     300000
104231          Yes           No           No     300000
104232          Yes          Yes          Yes     300000
104233           No           No           No     300000

[104234 rows x 88 columns]
Consumption Labels
         survey_id    hhid  cons_ppp17
0          100000  100001   25.258402
1          100000  100002   16.996706
2          100000  100003   13.671848
3          100000  100004    7.189475
4          100000  100005   12.308855
...           ...     ...         ...
104229     300000  337458    2.830888
104230     300000  337459    3.144309
104231     300000  337460    3.319158
104232     300000  337461    6.088739
104233     300000  337462    3.635263

[104234 rows x 3 columns]
Poverty rate
    survey_id  pct_hh_below_3.17  pct_hh_below_3.94  pct_hh_below_4.60  \
0     100000           0.067364           0.118927           0.169905
1     200000           0.059326           0.111560           0.159023
2     300000           0.049803           0.100381           0.149502

   pct_hh_below_5.26  pct_hh_below_5.88  pct_hh_below_6.47  pct_hh_below_7.06  \
0           0.221865           0.271564           0.319585           0.366329
1           0.211754           0.263100           0.311758           0.356914
2           0.200144           0.250192           0.300211           0.349596

   pct_hh_below_7.70  pct_hh_below_8.40  pct_hh_below_9.13  pct_hh_below_9.87  \
0           0.419816           0.471454           0.523798           0.574413
1           0.407631           0.463443           0.512931           0.559361
2           0.399930           0.449845           0.499930           0.550082

   pct_hh_below_10.70  pct_hh_below_11.62  pct_hh_below_12.69  \
0            0.623091            0.671263            0.721329
1            0.609337            0.659291            0.708043
2            0.599926            0.650088            0.699617

   pct_hh_below_14.03  pct_hh_below_15.64  pct_hh_below_17.76  \
0            0.773303            0.819770            0.865121
1            0.760932            0.809045            0.860350
2            0.750341            0.800111            0.850081

   pct_hh_below_20.99  pct_hh_below_27.37
0            0.909075            0.954239
1            0.906385            0.952805
2            0.899974            0.949988

##Analyze data

###Info

In [104]:
print("Survey features")
print(train_hsurvey_features.info())

Survey features
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104234 entries, 0 to 104233
Data columns (total 88 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   hhid               104234 non-null  int64
 1   com                104234 non-null  int64
 2   weight             104234 non-null  int64
 3   strata             104234 non-null  int64
 4   utl_exp_ppp17      104149 non-null  float64
 5   male               104234 non-null  object
 6   hsize              104234 non-null  int64
 7   num_children5      104234 non-null  int64
 8   num_children10     104234 non-null  int64
 9   num_children18     104234 non-null  int64
 10  age                104234 non-null  int64
 11  owner              104234 non-null  object
 12  water              104234 non-null  object
 13  toilet             104234 non-null  object
 14  sewer              104234 non-null  object
 15  elect              104234 non-null  object
 16  water_source       104234 non-null  object
 17  sanitation_source  104234 non-null  object
 18  dweltyp            103028 non-null  object
 19  num_adult_female   104234 non-null  int64
 20  num_adult_male     104234 non-null  int64
 21  num_elderly        104234 non-null  int64
 22  employed           104189 non-null  object
 23  sworkershh         104234 non-null  float64
 24  share_secondary    104211 non-null  float64
 25  educ_max           104211 non-null  object
 26  sfworkershh        104234 non-null  float64
 27  any_nonagric       104234 non-null  object
 28  sector1d           90105 non-null   object
 29  region1            104234 non-null  int64
 30  region2            104234 non-null  int64
 31  region3            104234 non-null  int64
 32  region4            104234 non-null  int64
 33  region5            104234 non-null  int64
 34  region6            104234 non-null  int64
 35  region7            104234 non-null  int64
 36  urban              104234 non-null  object
 37  consumed100        104232 non-null  object
 38  consumed200        104232 non-null  object
 39  consumed300        104232 non-null  object
 40  consumed400        104232 non-null  object
 41  consumed500        104232 non-null  object
 42  consumed600        104233 non-null  object
 43  consumed700        104232 non-null  object
 44  consumed800        104233 non-null  object
 45  consumed900        104233 non-null  object
 46  consumed1000       104230 non-null  object
 47  consumed1100       104230 non-null  object
 48  consumed1200       104229 non-null  object
 49  consumed1300       104229 non-null  object
 50  consumed1400       104229 non-null  object
 51  consumed1500       104231 non-null  object
 52  consumed1600       104230 non-null  object
 53  consumed1700       104229 non-null  object
 54  consumed1800       104230 non-null  object
 55  consumed1900       104230 non-null  object
 56  consumed2000       104231 non-null  object
 57  consumed2100       104230 non-null  object
 58  consumed2200       104227 non-null  object
 59  consumed2300       104231 non-null  object
 60  consumed2400       104233 non-null  object
 61  consumed2500       104230 non-null  object
 62  consumed2600       104227 non-null  object
 63  consumed2700       104232 non-null  object
 64  consumed2800       104229 non-null  object
 65  consumed2900       104227 non-null  object
 66  consumed3000       104224 non-null  object
 67  consumed3100       104221 non-null  object
 68  consumed3200       104219 non-null  object
 69  consumed3300       104214 non-null  object
 70  consumed3400       104212 non-null  object
 71  consumed3500       104210 non-null  object
 72  consumed3600       104211 non-null  object
 73  consumed3700       104205 non-null  object
 74  consumed3800       104199 non-null  object
 75  consumed3900       104194 non-null  object
 76  consumed4000       104196 non-null  object
 77  consumed4100       104194 non-null  object
 78  consumed4200       104190 non-null  object
 79  consumed4300       104182 non-null  object
 80  consumed4400       104182 non-null  object
 81  consumed4500       104180 non-null  object
 82  consumed4600       104178 non-null  object
 83  consumed4700       104182 non-null  object
 84  consumed4800       104178 non-null  object
 85  consumed4900       104178 non-null  object
 86  consumed5000       104168 non-null  object
 87  survey_id          104234 non-null  int64
dtypes: float64(4), int64(20), object(64)
memory usage: 70.0+ MB
None

###Missing values per col

In [105]:
print("Missing values")
print(train_hsurvey_features.isna().sum())

Missing values
hhid              0
com               0
weight            0
strata            0
utl_exp_ppp17    85
                 ..
consumed4700     52
consumed4800     56
consumed4900     56
consumed5000     66
survey_id         0
Length: 88, dtype: int64

###Descriptive Statistics

In [106]:
print(train_hsurvey_features.describe())

                hhid       com         weight         strata  utl_exp_ppp17  \
count  104234.000000  104234.0  104234.000000  104234.000000  104149.000000
mean   222499.501497       1.0     926.357254       4.424813     510.439284
std     83279.120172       0.0    1121.680081       2.429095     437.475542
min    100001.000000       1.0       2.000000       1.000000       0.000000
25%    126059.250000       1.0     270.000000       2.000000     190.115800
50%    219929.500000       1.0     582.000000       5.000000     411.917570
75%    311403.750000       1.0    1128.000000       7.000000     722.440060
max    337462.000000       1.0   23832.000000       8.000000    5880.471200

               hsize  num_children5  num_children10  num_children18  \
count  104234.000000  104234.000000   104234.000000   104234.000000
mean        3.611653       0.287872        0.338066        0.571004
std         1.927880       0.561682        0.598281        0.831472
min         1.000000       0.000000        0.000000        0.000000
25%         2.000000       0.000000        0.000000        0.000000
50%         3.000000       0.000000        0.000000        0.000000
75%         5.000000       0.000000        1.000000        1.000000
max        21.000000       5.000000        6.000000        6.000000

                 age  ...  share_secondary    sfworkershh        region1  \
count  104234.000000  ...    104211.000000  104234.000000  104234.000000
mean       52.589414  ...         0.228974       0.320479       0.232736
std        15.732361  ...         0.315510       0.400869       0.422577
min        15.000000  ...         0.000000       0.000000       0.000000
25%        41.000000  ...         0.000000       0.000000       0.000000
50%        52.000000  ...         0.000000       0.000000       0.000000
75%        64.000000  ...         0.500000       0.500000       0.000000
max        98.000000  ...         1.000000       1.000000       1.000000

             region2        region3        region4        region5  \
count  104234.000000  104234.000000  104234.000000  104234.000000
mean        0.157166       0.106395       0.053150       0.235959
std         0.363959       0.308344       0.224333       0.424599
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000       0.000000
max         1.000000       1.000000       1.000000       1.000000

             region6        region7      survey_id
count  104234.000000  104234.000000  104234.000000
mean        0.098653       0.115941  205059.769365
std         0.298197       0.320156   81587.641825
min         0.000000       0.000000  100000.000000
25%         0.000000       0.000000  100000.000000
50%         0.000000       0.000000  200000.000000
75%         0.000000       0.000000  300000.000000
max         1.000000       1.000000  300000.000000

[8 rows x 24 columns]

##Create new train set

Combine datasets regarding Individual households and  household-level consumption  based on the common features they have

In [107]:
merged_train_set = train_hsurvey_features.merge(train_hconsumption_labels, on=["survey_id","hhid"], how="left")
merged_train_set

,hhid,com,weight,strata,utl_exp_ppp17,male,hsize,num_children5,num_children10,num_children18,...,consumed4300,consumed4400,consumed4500,consumed4600,consumed4700,consumed4800,consumed4900,consumed5000,survey_id,cons_ppp17
0,100001,1,75,4,594.80627,Female,1,0,0,0,...,No,No,No,Yes,Yes,Yes,Yes,No,100000,25.258402
1,100002,1,150,4,1676.27230,Female,2,0,0,0,...,No,No,No,No,Yes,Yes,No,No,100000,16.996706
2,100003,1,375,4,506.93719,Male,5,0,0,2,...,Yes,No,Yes,Yes,Yes,Yes,No,Yes,100000,13.671848
3,100004,1,375,4,824.61786,Male,5,0,0,1,...,Yes,No,No,No,Yes,Yes,No,No,100000,7.189475
4,100005,1,525,4,351.47644,Male,7,1,0,0,...,No,No,Yes,No,Yes,Yes,Yes,No,100000,12.308855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104229,337458,1,616,7,143.58849,Female,4,2,1,0,...,No,No,No,No,Yes,Yes,No,Yes,300000,2.830888
104230,337459,1,616,7,268.44803,Female,4,0,0,1,...,No,No,No,No,Yes,No,No,No,300000,3.144309
104231,337460,1,1540,7,243.47612,Male,10,2,3,2,...,No,No,Yes,No,Yes,Yes,No,No,300000,3.319158
104232,337461,1,1232,7,337.12079,Male,8,0,0,3,...,Yes,No,Yes,No,No,Yes,Yes,Yes,300000,6.088739
104233,337462,1,154,7,243.47612,Female,1,0,0,0,...,No,No,Yes,No,Yes,No,No,No,300000,3.635263

Check for double entries

In [108]:

if(train_hsurvey_features.shape[0]== merged_train_set.shape[0]):
  print('No double entries')
else:
  print('Double entries')

No double entries

Check for duplicate keys in household consumption labels

In [109]:
print(train_hconsumption_labels.duplicated(["survey_id","hhid"]).sum())

0

Check for missing values in the household-level consumption to verify that the matching of houshold survey  and consumption labels is successful.

In [110]:
print(merged_train_set["cons_ppp17"].isnull().mean())

0.0

In [111]:
merged_train_set["cons_ppp17"].describe()

count    104234.000000
mean         11.555229
std          10.034225
min           0.359563
25%           5.439294
50%           8.774002
75%          14.216931
max         236.115680
Name: cons_ppp17, dtype: float64

Clean dataset labels

In [112]:
#Remove columns with highly repetative values
drop_cols = merged_train_set.columns[merged_train_set.nunique()==1]

#Remove survey_id,hhid,com
#Remove male as it creates a bias
drop_cols = list(drop_cols)+["survey_id","hhid","com","male"]

with open("drop_cols.txt", "w") as f:
    for col in drop_cols:
        f.write(col + "\n")

merged_train_set = merged_train_set.drop(columns=drop_cols)

One-Hot Encoding for categorial columns

In [113]:
one_hot_cols = []
for col in merged_train_set.columns:
   #check for categorical strings
   if merged_train_set[col].dtype.name in ['object','category']:
    #remove NaN values and note down the values of the col
    unique_values = merged_train_set[col].dropna().unique()
    if len(unique_values)== 2:
      one_hot_cols.append(col)
print(one_hot_cols)

for col in one_hot_cols:
  unique_values = merged_train_set[col].dropna().unique()
  merged_train_set[col] = merged_train_set[col].map({unique_values[0]:0, unique_values[1]:1})

['owner', 'water', 'toilet', 'sewer', 'elect', 'employed', 'any_nonagric', 'urban', 'consumed100', 'consumed200', 'consumed300', 'consumed400', 'consumed500', 'consumed600', 'consumed700', 'consumed800', 'consumed900', 'consumed1000', 'consumed1100', 'consumed1200', 'consumed1300', 'consumed1400', 'consumed1500', 'consumed1600', 'consumed1700', 'consumed1800', 'consumed1900', 'consumed2000', 'consumed2100', 'consumed2200', 'consumed2300', 'consumed2400', 'consumed2500', 'consumed2600', 'consumed2700', 'consumed2800', 'consumed2900', 'consumed3000', 'consumed3100', 'consumed3200', 'consumed3300', 'consumed3400', 'consumed3500', 'consumed3600', 'consumed3700', 'consumed3800', 'consumed3900', 'consumed4000', 'consumed4100', 'consumed4200', 'consumed4300', 'consumed4400', 'consumed4500', 'consumed4600', 'consumed4700', 'consumed4800', 'consumed4900', 'consumed5000']

In [114]:
merged_train_set

,weight,strata,utl_exp_ppp17,hsize,num_children5,num_children10,num_children18,age,owner,water,...,consumed4200,consumed4300,consumed4400,consumed4500,consumed4600,consumed4700,consumed4800,consumed4900,consumed5000,cons_ppp17
0,75,4,594.80627,1,0,0,0,75,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.258402
1,150,4,1676.27230,2,0,0,0,61,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,16.996706
2,375,4,506.93719,5,0,0,2,49,0,0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,13.671848
3,375,4,824.61786,5,0,0,1,58,1,0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,7.189475
4,525,4,351.47644,7,1,0,0,57,0,0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,12.308855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104229,616,7,143.58849,4,2,1,0,33,0,1,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,2.830888
104230,616,7,268.44803,4,0,0,1,48,0,1,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,3.144309
104231,1540,7,243.47612,10,2,3,2,54,0,1,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,3.319158
104232,1232,7,337.12079,8,0,0,3,49,0,1,...,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,6.088739
104233,154,7,243.47612,1,0,0,0,76,0,1,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,3.635263

In [115]:
# Find all non-numeric columns
non_numeric = merged_train_set.select_dtypes(exclude=['int64','float64']).columns
print("Non-numeric columns:", non_numeric)

Non-numeric columns: Index(['water_source', 'sanitation_source', 'dweltyp', 'educ_max', 'sector1d'], dtype='object')

In [116]:
# #Extensive one-hot encoding for long categorical strings
# categorical_cols = merged_train_set.select_dtypes(include=['object','category']).columns
# long_categorical_cols = [col for col in categorical_cols if col not in one_hot_cols]
# print(long_categorical_cols)


base_names = []
for col in merged_train_set.columns:
  for base in non_numeric:
    if base in col and base not in base_names:
      base_names.append(base)

print(base_names)

# Find all columns that are the  base_name or contain it
columns_to_dummify = [col for col in merged_train_set.columns if any(base in col for base in base_names)]

print(columns_to_dummify)
merged_train_set = pd.get_dummies(merged_train_set,columns=columns_to_dummify,drop_first=True)

#Convert bool to binary
bool_cols = merged_train_set.select_dtypes(include=['bool']).columns
for col in bool_cols:
    merged_train_set[col] = merged_train_set[col].astype(int)

merged_train_set

['water_source', 'sanitation_source', 'dweltyp', 'educ_max', 'sector1d']
['water_source', 'sanitation_source', 'dweltyp', 'educ_max', 'sector1d']

,weight,strata,utl_exp_ppp17,hsize,num_children5,num_children10,num_children18,age,owner,water,...,sector1d_Fishing,sector1d_Health and social work,sector1d_Hotels and restaurants,sector1d_Manufacturing,sector1d_Mining and quarrying,"sector1d_Other community, social and personal service activities",sector1d_Public administration and defence,"sector1d_Real estate, renting and business activities","sector1d_Transport, storage and communications",sector1d_Wholesale and retail trade
0,75,4,594.80627,1,0,0,0,75,0,0,...,0,0,0,0,0,0,0,0,0,0
1,150,4,1676.27230,2,0,0,0,61,0,0,...,0,0,0,0,0,0,0,0,0,0
2,375,4,506.93719,5,0,0,2,49,0,0,...,0,0,0,0,0,0,0,0,1,0
3,375,4,824.61786,5,0,0,1,58,1,0,...,0,0,0,0,0,0,1,0,0,0
4,525,4,351.47644,7,1,0,0,57,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104229,616,7,143.58849,4,2,1,0,33,0,1,...,0,0,1,0,0,0,0,0,0,0
104230,616,7,268.44803,4,0,0,1,48,0,1,...,0,0,0,0,0,0,0,0,0,0
104231,1540,7,243.47612,10,2,3,2,54,0,1,...,0,0,0,0,0,0,0,0,0,0
104232,1232,7,337.12079,8,0,0,3,49,0,1,...,0,0,0,0,0,0,0,0,0,1
104233,154,7,243.47612,1,0,0,0,76,0,1,...,0,0,0,0,0,0,0,0,0,0

In [117]:
#Total food consumption

In [118]:
total_consumtion = []
for col in merged_train_set.columns:
  if col.startswith("consumed"):
    total_consumtion.append(col)

merged_train_set["total_food_consumption"] = merged_train_set[total_consumtion].sum(axis=1)
merged_train_set = merged_train_set.drop(columns=total_consumtion)

###Mean number of children

In [119]:
children = []
for col in merged_train_set.columns:
  if col.startswith("num_children"):
    children.append(col)

merged_train_set["mean_num_children"] = merged_train_set[children].sum(axis=1)
merged_train_set = merged_train_set.drop(columns=children)

Mean of working  adults

In [120]:
employeed_adults = []
keywords = ["employed","sworkershh"]
for col in merged_train_set.columns:
  if any(k in col for k in keywords):
    employeed_adults.append(col)

merged_train_set["mean_employeed_adults"] = merged_train_set[employeed_adults].sum(axis=1)
merged_train_set = merged_train_set.drop(columns=employeed_adults)

In [121]:
merged_train_set

,weight,strata,utl_exp_ppp17,hsize,age,owner,water,toilet,sewer,elect,...,sector1d_Manufacturing,sector1d_Mining and quarrying,"sector1d_Other community, social and personal service activities",sector1d_Public administration and defence,"sector1d_Real estate, renting and business activities","sector1d_Transport, storage and communications",sector1d_Wholesale and retail trade,total_food_consumption,mean_num_children,mean_employeed_adults
0,75,4,594.80627,1,75,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,0,0.000000
1,150,4,1676.27230,2,61,0,0,0,0,0,...,0,0,0,0,0,0,0,19.0,0,0.000000
2,375,4,506.93719,5,49,0,0,0,0,0,...,0,0,0,0,0,1,0,18.0,2,1.666667
3,375,4,824.61786,5,58,1,0,0,0,1,...,0,0,0,1,0,0,0,22.0,1,2.250000
4,525,4,351.47644,7,57,0,0,0,0,0,...,0,0,0,0,0,0,0,18.0,1,1.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104229,616,7,143.58849,4,33,0,1,1,1,0,...,0,0,0,0,0,0,0,15.0,3,2.000000
104230,616,7,268.44803,4,48,0,1,1,1,0,...,0,0,0,0,0,0,0,18.0,1,0.000000
104231,1540,7,243.47612,10,54,0,1,0,1,0,...,0,0,0,0,0,0,0,14.0,7,1.000000
104232,1232,7,337.12079,8,49,0,1,1,1,0,...,0,0,0,0,0,0,1,18.0,3,2.000000
104233,154,7,243.47612,1,76,0,1,1,1,0,...,0,0,0,0,0,0,0,22.0,0,0.000000

Check for NaN values

In [122]:
num_cols = merged_train_set.select_dtypes(include=['int64','float64']).columns
for col in num_cols:
  merged_train_set[col].fillna(merged_train_set[col].median(), inplace=True)

cat_cols = merged_train_set.select_dtypes(include=['object','category']).columns
for col in cat_cols:
  merged_train_set[col].fillna(merged_train_set[col].mode()[0], inplace=True)

/tmp/ipython-input-748272659.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_train_set[col].fillna(merged_train_set[col].median(), inplace=True)

In [123]:
merged_train_set.isna().sum().sum()

np.int64(0)

##Save edited train set

In [124]:
merged_train_set.to_csv("edited_train_set.csv")